bind C-a send-prefix -2
bind 0 select-window -t :=10              # prefix + 0 -> window 10
bind -n C-l send-keys C-l \; clear-history
bind r source-file "C:/Users/al/.psmux.conf" \; display "Configuration reloaded"
bind e new-window -n "psmux.conf" -- notepad "C:/Users/al/.psmux.conf"
bind C-c new-session
bind C-f command-prompt -p "(find-session)" "switch-client -t %%"
bind BTab switch-client -l
bind - split-window -v
bind _ split-window -h
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind > swap-pane -D
bind < swap-pane -U
bind + resize-pane -Z
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2
unbind n
unbind p
bind -r C-h previous-window
bind -r C-l next-window
bind Tab last-window
bind m set -g mouse "#{?#{==:#{mouse},on},off,on}"
bind Enter copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send -X cancel
bind -T copy-mode-vi H send -X start-of-line
bind -T copy-mode-vi L send -X end-of-line
bind b list-buffers
bind p paste-buffer -p
bind P choose-buffer
bind T run-shell "C:/Users/al/.psmux-theme.cmd sync"
bind M-l run-shell "C:/Users/al/.psmux-theme.cmd light"
bind M-d run-shell "C:/Users/al/.psmux-theme.cmd dark"
