# ~/.psmux-theme-dark.conf — bảng màu oh-my-tmux gốc, dùng khi Windows ở dark mode
#  1 #080808 dark gray   2 #303030 gray      3 #8a8a8a light gray
#  4 #00afff light blue  5 #ffff00 yellow    7 #e4e4e4 white
# 10 #ff00af pink       11 #5fff00 green    16 #d70000 red

set -g status-style "fg=#8a8a8a,bg=#080808,none"
set -g message-style "fg=#080808,bg=#ffff00,bold"
set -g message-command-style "fg=#ffff00,bg=#080808,bold"
set -g mode-style "fg=#080808,bg=#ffff00"

set -g pane-border-style "fg=#303030"
set -g pane-active-border-style "fg=#00afff"

set -g window-status-style "fg=#8a8a8a,bg=#080808,none"
set -g window-status-current-style "fg=#080808,bg=#00afff,bold"
set -g window-status-last-style "fg=#00afff,bg=#303030,none"
set -g window-status-activity-style "fg=#8a8a8a,bg=#080808,underscore"
set -g window-status-bell-style "fg=#ffff00,bg=#080808,blink,bold"

set -g status-left "#[fg=#080808,bg=#ffff00,bold] ❐ #S #[fg=#e4e4e4,bg=#ff00af,none] #{b:pane_current_path} #[fg=#8a8a8a,bg=#080808,none] "
set -g status-right "#[fg=#8a8a8a,bg=#080808,none] #{?client_prefix,⌨ ,}#{?#{==:#{mouse},on},↗ ,}#{?#{==:#{synchronize-panes},on},⚏ ,}%R | %d %b #[fg=#e4e4e4,bg=#d70000,none] #{user} #[fg=#080808,bg=#e4e4e4,bold] #{host_short} "
