# ~/.psmux-theme-dark.conf — bảng màu oh-my-tmux gốc, dùng khi Windows ở dark mode
#  1 #080808 dark gray   2 #303030 gray      3 #8a8a8a light gray
#  4 #00afff light blue  5 #ffff00 yellow    7 #e4e4e4 white
# 10 #ff00af pink       11 #5fff00 green    16 #d70000 red

set -g status-style "fg=#8a8a8a,bg=#080808,none"
set -g message-style "fg=#080808,bg=#ffff00,bold"
set -g message-command-style "fg=#ffff00,bg=#080808,bold"
set -g mode-style "fg=#080808,bg=#ffff00"

set -g pane-border-style "fg=#303030"
set -g pane-active-border-style "fg=#00afff"

set -g window-status-style "fg=#8a8a8a,bg=#080808,none"
set -g window-status-current-style "fg=#080808,bg=#00afff,bold"
set -g window-status-last-style "fg=#00afff,bg=#303030,none"
set -g window-status-activity-style "fg=#8a8a8a,bg=#080808,underscore"
set -g window-status-bell-style "fg=#ffff00,bg=#080808,blink,bold"

set -g status-left "#[fg=#080808,bg=#ffff00,bold] ❐ #S #[fg=#e4e4e4,bg=#ff00af,none] #{b:pane_current_path} #[fg=#8a8a8a,bg=#080808,none] "
set -g status-right "#[fg=#8a8a8a,bg=#080808,none] #{?client_prefix,⌨ ,}#{?#{==:#{mouse},on},↗ ,}#{?#{==:#{synchronize-panes},on},⚏ ,}#{@bat_pre}#[fg=#ff0000]#{@bat_c1}#[fg=#ff3900]#{@bat_c2}#[fg=#ff7100]#{@bat_c3}#[fg=#ffaa00]#{@bat_c4}#[fg=#ffe300]#{@bat_c5}#[fg=#e3ff00]#{@bat_c6}#[fg=#aaff00]#{@bat_c7}#[fg=#71ff00]#{@bat_c8}#[fg=#39ff00]#{@bat_c9}#[fg=#00ff00]#{@bat_c10}#[fg=#585858]#{@bat_rest}#[fg=#ff0000]#{@bat_t1}#[fg=#ff3900]#{@bat_t2}#[fg=#ff7100]#{@bat_t3}#[fg=#ffaa00]#{@bat_t4}#[fg=#ffe300]#{@bat_t5}#[fg=#e3ff00]#{@bat_t6}#[fg=#aaff00]#{@bat_t7}#[fg=#71ff00]#{@bat_t8}#[fg=#39ff00]#{@bat_t9}#[fg=#00ff00]#{@bat_t10}#[fg=#8a8a8a,bg=#080808,none]#{@bat_post}%R | %d %b #[fg=#e4e4e4,bg=#d70000,none] #{user} #[fg=#080808,bg=#e4e4e4,bold] #{host_short} "
